config/routes.rb
Rails.application.routes.draw do
  get 'render/index'
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  get 'home/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user #o @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:image, :title, :description)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="col-md-4 mb-4">
  <div class="card" style="border-radius: 10px; overflow: hidden;">
    <%= image_tag(asset_path(post.image), class: "card-img-top", style: "border-radius: 0;") %>
    <div class="card-body">
      <h5 class="card-title"><%= post.title %></h5>
      <p class="card-text"><%= post.description %></p>
      <%= link_to "Show this post", post, class: "btn btn-warning" %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 style="color: white">Posts</h1>

<div class="posts-container">
  <% @posts.each do |post| %>
    <div class="post-card">
      <%= image_tag(post.image, class: "your-custom-class") %>
      <h2><%= post.title %></h2>
      <p><strong>Description:</strong> <%= post.description %></p>
      <%= link_to "Ver este post", post %>
    </div>
  <% end %>
</div>
<div class="button-container">
  <%= link_to "POSTEAR", new_post_path, class: "btn-teal" %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Back to posts", posts_path %> |

  <% if user_signed_in? %>
    <% if current_user.id == @post.user_id %>
      <%= link_to "Edit this post", edit_post_path(@post) %>
      <%= button_to "Destroy this post", @post, method: :delete %>
    <% end %>
  <% end %>

</div>
<hr/>
<div class="container">
<% if user_signed_in? %>
<h2>Deja tu comentario</h2>
  <%= form_with(model: [ @post, @post.comments.build ], local: true) do |form| %>
      <div class="form-group">
        <%= form.label :content, "Deja un comentario:" %>
        <%= form.text_area :content, class: "form-control" %>
      </div><br/>
      <%= form.submit "Comentar", class: "btn btn-primary" %>
  <% end %>
<% end %>
<h3>Comentarios existentes:</h3>
<% @post.comments.each do |comment| %>
  <div class="comment">
    <% if comment.user %>
      <strong><%= comment.user.email %></strong> comentó:
    <% else %>
    <div class="d-none">
      <strong>Usuario desconocido</strong> comentó:
    <% end %>
      <%= comment.content %>
    </div>
     <% if user_signed_in? && current_user == comment.user %> <!-- Verifica si hay un usuario logueado y si es el dueño del comentario -->
      <%= form_with(url: post_comment_path(@post, comment), method: :delete, data: { confirm: '¿Estás seguro de que deseas eliminar este comentario?' }, class: 'inline-form') do %>
        <%= submit_tag 'Eliminar', class: 'btn btn-danger' %>
      <% end %>
    <% end %>
  </div>
</div>
<% end %>